[project]
nav = [
  {"MAA" = [
    {"首页" = "index.md"},
    {"编辑手册" = "zensical_markdown.md"},
    {"待办" = "to-do.md"},
    {"临时" = [
      {"Voron" = "other/voron_project.md"},
    ]},
  ]},

  {"RadioFrequency" = [
    # {"测试页面" = "rf/rf_text.md"},
    {"射频与高速数字基础" = "rf/射频与高速数字基础.md"}
  ]},

  {"Embedded" = [
    {"快速查阅" = [
      {"AWG与mm线径&电流换算" = "embedded/awgtomm.md"}
    ]}
  ]},

  {"Aerospace" = [
    {"测试页面" = "aerospace/aerospace.md"}
  ]},
  
  {"其它" = [
    {"配置终端代理" = "other/terminal_proxy.md"}
  ]}
]


# 站点名
site_name = "JRNitre'sLibrary"
# 站点简介
site_description = "nullptr."
# 站点作者
site_author = "JRNitre"
# 站点 URL
site_url = "https://jrnitre.github.io/"
# 版权声明
copyright = "&copy; 2026 The JRNitre"

repo_url = "https://github.com/JRNitre/jrnitre.github.io"
repo_name = "JRNitre'sLibrary"

use_directory_urls = false

extra_css = ["stylesheets/extra.css"]

[project.theme]
language = "zh"
font.text = "HarmonyOS"
font.code = "MapleMono"

features = [
    "navigation.tabs",
    "navigation.sections",
    "navigation.indexes",
    "navigation.path",
    "toc.integrate",
    "navigation.top",
    "content.code.copy"
]

[project.theme.icon]
repo = "fontawesome/brands/github"

[[project.theme.palette]]
scheme = "slate"
primary = "orange"
accent = "deep orange"
toggle.icon = "lucide/sun"

[[project.theme.palette]]
scheme = "default"
primary = "orange"
accent = "deep orange"
toggle.icon = "lucide/moon"

[[project.extra.social]]
icon = "fontawesome/brands/github"
link = "https://github.com/JRNitre"

[project.markdown_extensions.pymdownx.caret]
[project.markdown_extensions.pymdownx.keys]
[project.markdown_extensions.pymdownx.mark]
[project.markdown_extensions.pymdownx.tilde]
[project.markdown_extensions.attr_list]

[project.markdown_extensions.pymdownx.highlight]
anchor_linenums = true
line_spans = "__span"
pygments_lang_class = true
[project.markdown_extensions.pymdownx.inlinehilite]
[project.markdown_extensions.pymdownx.snippets]
[project.markdown_extensions.pymdownx.superfences]

[project.markdown_extensions.def_list]
[project.markdown_extensions.pymdownx.tasklist]
custom_checkbox = true