[project]
nav = [
  {"Home" = "index.md"}
]


# 站点名
site_name = "JRNitre'sLibrary"
# 站点简介
site_description = "nullptr."
# 站点作者
site_author = "JRNitre"
# 站点 URL
site_url = "https://jrnitre.github.io/"
# 版权声明
copyright = "&copy; 2026 The JRNitre"

repo_url = "https://github.com/JRNitre/jrnitre.github.io"
repo_name = "JRNitre'sLibrary"

use_directory_urls = false

extra_css = ["stylesheets/extra.css"]

[project.theme]
language = "zh"
font.text = "HarmonyOS"
font.code = "MapleMono"

features = [
    "navigation.tabs",
    "navigation.sections",
    "navigation.path",
    "toc.integrate",
    "navigation.top"
]

[project.theme.icon]
repo = "fontawesome/brands/github"

[[project.theme.palette]]
media = "(prefers-color-scheme: light)"
scheme = "default"
primary = "orange"
accent = "deep orange"
toggle.icon = "lucide/sun"

[[project.theme.palette]]
media = "(prefers-color-scheme: light)"
scheme = "slate"
primary = "orange"
accent = "deep orange"
toggle.icon = "lucide/moon"

[[project.extra.social]]
icon = "fontawesome/brands/github"
link = "https://github.com/JRNitre"