[project]
nav = [
  {"MAA" = [
    {"首页" = "index.md"},
    {"编辑手册" = "zensical_markdown.md"},
    {"GitConventionalCommits" = "other/git_conventional_commits.md"},
    {"待办" = "to-do.md"},
    {"临时" = [
      {"Voron" = "other/voron_project.md"},
    ]},
  ]},

  {"RadioFrequency" = [
    # {"测试页面" = "rf/rf_text.md"},
    {"射频与高速数字基础" = "rf/射频与高速数字基础.md"}
  ]},

  {"Embedded" = [
    {"快速查阅" = [
      {"AWG与mm线径&电流换算" = "embedded/awgtomm.md"}
    ]}
  ]},

  {"Aerospace" = [
    {"Rhino" = [
      {"插件与基础设置" = "aerospace/rhino/01.md"},
      {"快捷键映射" = "aerospace/rhino/02.md"},
    ]}
  ]},
  
  {"其它" = [
    {"配置终端代理" = "other/terminal_proxy.md"}
  ]}
]

# === === ===

site_name = "JRNitre'sLibrary"  # 站点名
site_description = "nullptr."   # 站点简介
# 站点作者
site_author = "JRNitre"
# 站点 URL
site_url = "https://jrnitre.cn"
# 版权声明
copyright = "&copy; 2026 The JRNitre"
repo_url = "https://github.com/JRNitre/jrnitre.github.io"
repo_name = "JRNitre'sLibrary"
use_directory_urls = false
extra_css = ["stylesheets/extra.css"]

[project.theme]
language = "zh"
font.text = "HarmonyOS"
font.code = "MapleMono"
features = [
    "navigation.tabs",
    "navigation.sections",
    "navigation.indexes",
    "navigation.path",
    "toc.integrate",
    "navigation.top",
    "content.tooltips",
    "content.code.copy"
]
  

[project.theme.icon]
repo = "fontawesome/brands/github"

[[project.theme.palette]]
scheme = "slate"
primary = "orange"
accent = "deep orange"
toggle.icon = "lucide/sun"

[[project.theme.palette]]
scheme = "default"
primary = "orange"
accent = "deep orange"
toggle.icon = "lucide/moon"

[[project.extra.social]]
icon = "fontawesome/brands/github"
link = "https://github.com/JRNitre"

[project.markdown_extensions]
pymdownx.highlight.anchor_linenums = true
pymdownx.highlight.line_spans = "_span"
pymdownx.highlight.pygments_lang_class = true
pymdownx.superfences = {}
pymdownx.inlinehilite = {}
pymdownx.caret = {}
pymdownx.keys = {}
pymdownx.mark = {}
pymdownx.tilde = {}
pymdownx.snippets = {}
pymdownx.tasklist.custom_checkbox = true
pymdownx.details = {}
pymdownx.emoji.emoji_generator = "zensical.extensions.emoji.to_svg"
pymdownx.emoji.emoji_index = "zensical.extensions.emoji.twemoji"
attr_list = {}
md_in_html = {}
def_list = {}
admonition = {}
abbr = {}
